name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code to a GOPATH compatible directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/dougsland/jenkinsctl
        
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
        
    - name: Debug
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}

    - name: Make
      run: |
        cd go/src/github.com/dougsland/jenkinsctl
        env GOOS=linux GOARCH=amd64 go build -v -o jenkinsctl_linux_amd64 -ldflags="-s -w -X main.version=latest" jenkinsctl.go

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
          name: code-coverage-report
          path: go/bin/jenkinsctl*
