name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
        
    - name: Debug
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}
